name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13

    - name: Publish for win-x64
      run: dotnet publish -c Release -r win-x64
    - name: Publish for osx-x64
      run: dotnet publish -c Release -r osx-x64
    - name: Publish for linux-x64
      run: dotnet publish -c Release -r linux-x64
    - name: Pack library
      run: dotnet pack -c Release WadLib

    - name: Upload nupkg
      uses: actions/upload-artifact@v3.1.0
      with:
        name: nightly-nupkg
        path: WadLib/bin/Release/*.nupkg
    - name: Upload win-x64 build
      uses: actions/upload-artifact@v3.1.0
      with:
        name: nightly-win-x64
        path: WadTool/bin/Release/net6.0/win-x64/publish/wadtool.exe
    - name: Upload osx-x64 build
      uses: actions/upload-artifact@v3.1.0
      with:
        name: nightly-osx-x64
        path: WadTool/bin/Release/net6.0/osx-x64/publish/wadtool
    - name: Upload linux-x64 build
      uses: actions/upload-artifact@v3.1.0
      with:
        name: nightly-linux-x64
        path: WadTool/bin/Release/net6.0/linux-x64/publish/wadtool
